# Generated by Django 5.0.4 on 2024-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_comment_user_introduce"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="garde",
            field=models.CharField(
                choices=[
                    ("B", "Bronze"),
                    ("S", "Silver"),
                    ("G", "Gold"),
                    ("D", "Diamond"),
                ],
                default="B",
                max_length=1,
            ),
        ),
    ]
