# Generated by Django 5.0.4 on 2024-04-15 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_garde"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="garde",
            new_name="grade",
        ),
    ]
