# Generated by Django 5.0.4 on 2024-04-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="point",
            field=models.IntegerField(default=10000),
        ),
    ]
