# Generated by Django 5.0.4 on 2024-04-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
    ]
