# Generated by Django 5.0.4 on 2024-04-15 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_products_sale_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="likey",
            field=models.ManyToManyField(
                blank=True, related_name="likey", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="products",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
