# Generated by Django 5.0.4 on 2024-04-17 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_wishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="wishuser",
            field=models.ManyToManyField(
                blank=True, related_name="wishprod", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
