# Generated by Django 5.0.4 on 2024-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_products_wishuser_delete_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="hashtags", to="products.products"
                    ),
                ),
            ],
        ),
    ]
