# Generated by Django 5.0.4 on 2024-04-18 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_buyer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Buyer",
        ),
    ]
