# Generated by Django 5.0.4 on 2024-04-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_buylist"),
    ]

    operations = [
        migrations.AddField(
            model_name="buylist",
            name="priced",
            field=models.IntegerField(default=0),
        ),
    ]
